using AI.CodeAgent.Builder.Domain.Common;
using AI.CodeAgent.Builder.Domain.Entities;

namespace AI.CodeAgent.Builder.Application.Common.Interfaces.Persistence;

/// <summary>
/// Repository interface for Category aggregate root.
/// Defines category-specific query and persistence operations.
/// </summary>
public interface ICategoryRepository : IRepository<Category>
{
    /// <summary>
    /// Retrieves all active categories ordered by name.
    /// </summary>
    Task<IEnumerable<Category>> GetAllActiveCategoriesAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves a category by its unique name.
    /// </summary>
    Task<Category?> GetByNameAsync(string name, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a category with the given name already exists.
    /// </summary>
    Task<bool> ExistsByNameAsync(string name, CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves categories generated by AI.
    /// </summary>
    Task<IEnumerable<Category>> GetAIGeneratedCategoriesAsync(CancellationToken cancellationToken = default);
}
